server:
  port: 8081

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manager?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
      host: 127.0.0.1
      password:
      port: 6379
      timeout: 50000 # 连接超时时间（毫秒）
      database: 0 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
      lettuce:
        pool:
          max-active: 8 # 连接池最大连接数（使用负值表示没有限制）默认 8
          max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）默认 -1
          max-idle: 8 # 连接池中的最大空闲连接默认 8
          min-idle: 0 # 连接池中的最小空闲连接默认 0


base:
  security:
    browser:
      loginPage: /login.html
      lsType: JSON
    login:
      mapping: {username: getRecordByUsername, phone: getRecordByPhone}
    code:
      store_type: redis
      validateUrl: /login,/login/phone,/register/**
      image:
        type: GIF
        width: 130
        height: 48
        length: 4
        expire: 300
        size: 32

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
